/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente_PCK;

/**
 *
 * @author ASUS
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_GESTION_CLIENTE = new javax.swing.JTabbedPane();
        jp_CREAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_crearC_cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_crearC_cedula1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_crearC_cedula2 = new javax.swing.JTextField();
        tf_crearC_cedula3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_crearC_cedula4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jp_LISTAR = new javax.swing.JPanel();
        jp_CONSULTAR = new javax.swing.JPanel();
        jp_ACTUALIZAR = new javax.swing.JPanel();
        jp_ELIMINAR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cédula:");

        tf_crearC_cedula.setColumns(10);

        jLabel2.setText("Cédula:");

        tf_crearC_cedula1.setColumns(10);

        jLabel3.setText("Cédula:");

        tf_crearC_cedula2.setColumns(10);

        tf_crearC_cedula3.setColumns(10);

        jLabel4.setText("Cédula:");

        tf_crearC_cedula4.setColumns(10);

        jLabel5.setText("Cédula:");

        jLabel6.setText("Cédula:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        javax.swing.GroupLayout jp_CREARLayout = new javax.swing.GroupLayout(jp_CREAR);
        jp_CREAR.setLayout(jp_CREARLayout);
        jp_CREARLayout.setHorizontalGroup(
            jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CREARLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_CREARLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(112, 112, 112)
                        .addComponent(tf_crearC_cedula4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jp_CREARLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(112, 112, 112)
                            .addComponent(tf_crearC_cedula3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_CREARLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(112, 112, 112)
                                .addComponent(tf_crearC_cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_CREARLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(112, 112, 112)
                                .addComponent(tf_crearC_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jp_CREARLayout.createSequentialGroup()
                            .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(112, 112, 112)
                            .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_crearC_cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jp_CREARLayout.setVerticalGroup(
            jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CREARLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_crearC_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_crearC_cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_crearC_cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_crearC_cedula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jp_CREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_crearC_cedula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        tp_GESTION_CLIENTE.addTab("Crear cliente", jp_CREAR);

        javax.swing.GroupLayout jp_LISTARLayout = new javax.swing.GroupLayout(jp_LISTAR);
        jp_LISTAR.setLayout(jp_LISTARLayout);
        jp_LISTARLayout.setHorizontalGroup(
            jp_LISTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jp_LISTARLayout.setVerticalGroup(
            jp_LISTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        tp_GESTION_CLIENTE.addTab("Listar todos los clientes", jp_LISTAR);

        javax.swing.GroupLayout jp_CONSULTARLayout = new javax.swing.GroupLayout(jp_CONSULTAR);
        jp_CONSULTAR.setLayout(jp_CONSULTARLayout);
        jp_CONSULTARLayout.setHorizontalGroup(
            jp_CONSULTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jp_CONSULTARLayout.setVerticalGroup(
            jp_CONSULTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        tp_GESTION_CLIENTE.addTab("Consultar cliente", jp_CONSULTAR);

        javax.swing.GroupLayout jp_ACTUALIZARLayout = new javax.swing.GroupLayout(jp_ACTUALIZAR);
        jp_ACTUALIZAR.setLayout(jp_ACTUALIZARLayout);
        jp_ACTUALIZARLayout.setHorizontalGroup(
            jp_ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jp_ACTUALIZARLayout.setVerticalGroup(
            jp_ACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        tp_GESTION_CLIENTE.addTab("Actualizar datos cliente", jp_ACTUALIZAR);

        javax.swing.GroupLayout jp_ELIMINARLayout = new javax.swing.GroupLayout(jp_ELIMINAR);
        jp_ELIMINAR.setLayout(jp_ELIMINARLayout);
        jp_ELIMINARLayout.setHorizontalGroup(
            jp_ELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jp_ELIMINARLayout.setVerticalGroup(
            jp_ELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        tp_GESTION_CLIENTE.addTab("Eliminar cliente", jp_ELIMINAR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_GESTION_CLIENTE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_GESTION_CLIENTE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jp_ACTUALIZAR;
    private javax.swing.JPanel jp_CONSULTAR;
    private javax.swing.JPanel jp_CREAR;
    private javax.swing.JPanel jp_ELIMINAR;
    private javax.swing.JPanel jp_LISTAR;
    private javax.swing.JTextField tf_crearC_cedula;
    private javax.swing.JTextField tf_crearC_cedula1;
    private javax.swing.JTextField tf_crearC_cedula2;
    private javax.swing.JTextField tf_crearC_cedula3;
    private javax.swing.JTextField tf_crearC_cedula4;
    private javax.swing.JTabbedPane tp_GESTION_CLIENTE;
    // End of variables declaration//GEN-END:variables
}
